/**
 * Stable machine codes the client renders distinctly (TRD §6.2).
 * Adding a code here is a contract change: the Flutter client switches on it.
 */
export const ErrorCode = {
  SEAT_FILLED: 'SEAT_FILLED',
  SHIFT_CANCELLED: 'SHIFT_CANCELLED',
  OVERLAPPING_BOOKING: 'OVERLAPPING_BOOKING',
  OUTSIDE_GEOFENCE: 'OUTSIDE_GEOFENCE',
  OUTSIDE_WINDOW: 'OUTSIDE_WINDOW',
  LOCATION_ACCURACY_LOW: 'LOCATION_ACCURACY_LOW',
  INTEGRITY_REJECTED: 'INTEGRITY_REJECTED',
  INVALID_CODE: 'INVALID_CODE',
  SESSION_SUPERSEDED: 'SESSION_SUPERSEDED',
  NOT_VETTED: 'NOT_VETTED',
  OFFER_EXPIRED: 'OFFER_EXPIRED',
  RATE_LIMITED: 'RATE_LIMITED',

  // Protocol-level codes, not in the PRD's client-rendered list.
  IDEMPOTENCY_KEY_REUSED: 'IDEMPOTENCY_KEY_REUSED',
  REQUEST_IN_FLIGHT: 'REQUEST_IN_FLIGHT',
  ILLEGAL_TRANSITION: 'ILLEGAL_TRANSITION',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL: 'INTERNAL',
} as const;

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];

/** Non-negotiable default HTTP status per code, so handlers cannot drift. */
export const ERROR_STATUS: Record<ErrorCodeValue, number> = {
  SEAT_FILLED: 409,
  SHIFT_CANCELLED: 409,
  OVERLAPPING_BOOKING: 409,
  OUTSIDE_GEOFENCE: 422,
  OUTSIDE_WINDOW: 422,
  LOCATION_ACCURACY_LOW: 422,
  INTEGRITY_REJECTED: 422,
  INVALID_CODE: 422,
  SESSION_SUPERSEDED: 401,
  NOT_VETTED: 403,
  OFFER_EXPIRED: 410,
  RATE_LIMITED: 429,

  IDEMPOTENCY_KEY_REUSED: 409,
  REQUEST_IN_FLIGHT: 409,
  ILLEGAL_TRANSITION: 409,
  VALIDATION_FAILED: 400,
  UNAUTHENTICATED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  INTERNAL: 500,
};
